"""password to binary

Revision ID: 34b07e61e352
Revises: 67f9e02f91e0
Create Date: 2024-04-16 16:27:11.806795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b07e61e352'
down_revision = '67f9e02f91e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
